solve_01: .solve_01
solve_02: .solve_02
solve_03: .solve_03
solve_04: .solve_04
solve_05: .solve_05
solve_06: .solve_06
solve_07: .solve_07
solve_08: .solve_08
solve_09: .solve_09
solve_10: .solve_10
solve_11: .solve_11
solve_12: .solve_12
solve_13: .solve_13
solve_14: .solve_14
solve_15: .solve_15
solve_16: .solve_16
solve_17: .solve_17
solve_18: .solve_18
solve_19: .solve_19
solve_20: .solve_20
solve_21: .solve_21
solve_22: .solve_22
solve_23: .solve_23
solve_24: .solve_24
solve_25: .solve_25

.solve_%:
	@echo " ** solving day $* **"
	@cd day$* && python3 solution.py
	@echo ""

solve_all: \
	.solve_01
#	.solve_02 \
#	.solve_03 \
#	.solve_04 \
#	.solve_05 \
#	.solve_06 \
#	.solve_07 \
#	.solve_08 \
#	.solve_09 \
#	.solve_10 \
#	.solve_11 \
#	.solve_12 \
#	.solve_13 \
#	.solve_14 \
#	.solve_15 \
#	.solve_16 \
#	.solve_17 \
#	.solve_18 \
#	.solve_19 \
#	.solve_20 \
#	.solve_21 \
#	.solve_22 \
#	.solve_23 \
#	.solve_24 \
#	.solve_25
